import { Category, Product, Translation } from "./types";

export const CATEGORIES: { id: Category; label: Translation[string] }[] = [
  { id: 'paintings', label: { en: 'Tribal Paintings', hi: 'आदिवासी चित्रकला', mr: 'आदिवासी पेंटिंग्ज' } },
  { id: 'handicrafts', label: { en: 'Handicrafts', hi: 'हस्तशिल्प', mr: 'हस्तकला' } },
  { id: 'statues', label: { en: 'Statues', hi: 'मूर्तियाँ', mr: 'मूर्ती' } },
  { id: 'minerals', label: { en: 'Minor Minerals', hi: 'लघु खनिज', mr: 'गौण खनिजे' } },
  { id: 'fruits', label: { en: 'Forest Fruits', hi: 'वन फल', mr: 'वन फळे' } },
  { id: 'clothing', label: { en: 'Traditional Clothing', hi: 'पारंपरिक वस्त्र', mr: 'पारंपारिक कपडे' } },
  { id: 'instruments', label: { en: 'Musical Instruments', hi: 'वाद्य यंत्र', mr: 'वाद्ये' } },
  { id: 'cultural', label: { en: 'Cultural Items', hi: 'सांस्कृतिक वस्तुएं', mr: 'सांस्कृतिक वस्तू' } },
];

export const TRANSLATIONS: Translation = {
  appName: { en: 'TribalHeritage', hi: 'जनजातीय धरोहर', mr: 'आदिवासी वारसा' },
  search: { en: 'Search for products...', hi: 'उत्पाद खोजें...', mr: 'उत्पादने शोधा...' },
  login: { en: 'Login', hi: 'लॉग इन', mr: 'लॉग इन' },
  logout: { en: 'Logout', hi: 'लॉग आउट', mr: 'लॉग आउट' },
  cart: { en: 'Cart', hi: 'कार्ट', mr: 'कार्ट' },
  home: { en: 'Home', hi: 'होम', mr: 'होम' },
  shop: { en: 'Shop', hi: 'दुकान', mr: 'खरेदी' },
  dashboard: { en: 'Dashboard', hi: 'डैशबोर्ड', mr: 'डॅशबोर्ड' },
  addProduct: { en: 'Add Product', hi: 'उत्पाद जोड़ें', mr: 'उत्पादन जोडा' },
  myOrders: { en: 'My Orders', hi: 'मेरे ऑर्डर', mr: 'माझ्या ऑर्डर्स' },
  checkout: { en: 'Checkout', hi: 'चेकआउट', mr: 'चेकआउट' },
  total: { en: 'Total', hi: 'कुल', mr: 'एकूण' },
  addToCart: { en: 'Add to Cart', hi: 'कार्ट में डालें', mr: 'कार्टमध्ये टाका' },
  buyNow: { en: 'Buy Now', hi: 'अभी खरीदें', mr: 'आत्ता खरेदी करा' },
  seller: { en: 'Seller', hi: 'विक्रेता', mr: 'विक्रेता' },
  description: { en: 'Description', hi: 'विवरण', mr: 'वर्णन' },
  aiHelp: { en: 'AI Magic Help', hi: 'AI मदद', mr: 'AI मदत' },
  generating: { en: 'Generating...', hi: 'बना रहा है...', mr: 'तयार करत आहे...' },
  welcome: { en: 'Welcome', hi: 'स्वागत है', mr: 'स्वागत आहे' },
  heroTitle: { en: 'Authentic Tribal Treasures', hi: 'प्रामाणिक आदिवासी खजाने', mr: 'अस्सल आदिवासी ठेवा' },
  heroSubtitle: { en: 'Direct from artisans to your home.', hi: 'कारीगरों से सीधे आपके घर तक।', mr: 'कारागीरांकडून थेट तुमच्या घरी.' },
  emptyCart: { en: 'Your cart is empty', hi: 'आपकी कार्ट खाली है', mr: 'तुमची कार्ट रिकामी आहे' },
  placeOrder: { en: 'Place Order', hi: 'ऑर्डर करें', mr: 'ऑर्डर द्या' },
  orderSuccess: { en: 'Order Placed Successfully!', hi: 'ऑर्डर सफलतापूर्वक दी गई!', mr: 'ऑर्डर यशस्वीरित्या दिली गेली!' },
};

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    sellerId: 's1',
    title: 'Warli Painting Canvas',
    description: 'Authentic hand-painted Warli art depicting a village festival. Made with natural rice paste on treated canvas.',
    price: 1500,
    category: 'paintings',
    image: 'https://picsum.photos/400/400?random=1',
    stock: 5,
  },
  {
    id: '2',
    sellerId: 's2',
    title: 'Bamboo Flute Set',
    description: 'Set of 3 professional bamboo flutes tuned to different scales. Handcrafted by tribal artisans.',
    price: 850,
    category: 'instruments',
    image: 'https://picsum.photos/400/400?random=2',
    stock: 12,
  },
  {
    id: '3',
    sellerId: 's1',
    title: 'Dhokra Brass Statue',
    description: 'Ancient lost-wax casting technique used to create this stunning brass tribal horse statue.',
    price: 3200,
    category: 'statues',
    image: 'https://picsum.photos/400/400?random=3',
    stock: 2,
  },
  {
    id: '4',
    sellerId: 's3',
    title: 'Forest Honey (500g)',
    description: 'Pure, organic wild honey collected from the deep forests. No added sugar or preservatives.',
    price: 450,
    category: 'fruits',
    image: 'https://picsum.photos/400/400?random=4',
    stock: 50,
  },
];
